# Generated by Django 4.2.30 on 2026-06-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.PositiveBigIntegerField()),
                ('repository_link', models.URLField()),
                ('image', models.ImageField(upload_to='imgproject/')),
                ('skills', models.ManyToManyField(to='projects.skills')),
            ],
        ),
    ]
